// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCKlp8YlLYAktqCaMPZJgTeDbE99rsAeCo',
    appId: '1:142712906657:web:894571abf272c17e3f21e0',
    messagingSenderId: '142712906657',
    projectId: 'project-175f3',
    authDomain: 'project-175f3.firebaseapp.com',
    storageBucket: 'project-175f3.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC-dmpIne-SN6j_kvb1qtI9vIlVR-3IZoA',
    appId: '1:142712906657:android:072d84cad169705d3f21e0',
    messagingSenderId: '142712906657',
    projectId: 'project-175f3',
    storageBucket: 'project-175f3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAv0lzIgBk4cTbAUJYZRLagXW1tL4IlwkM',
    appId: '1:142712906657:ios:85d8147eb3bf25383f21e0',
    messagingSenderId: '142712906657',
    projectId: 'project-175f3',
    storageBucket: 'project-175f3.firebasestorage.app',
    iosBundleId: 'com.herzog.theMarchProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAv0lzIgBk4cTbAUJYZRLagXW1tL4IlwkM',
    appId: '1:142712906657:ios:85d8147eb3bf25383f21e0',
    messagingSenderId: '142712906657',
    projectId: 'project-175f3',
    storageBucket: 'project-175f3.firebasestorage.app',
    iosBundleId: 'com.herzog.theMarchProject',
  );
}
