import 'package:flutter/services.dart';
import 'package:intl/intl.dart';
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;

import '../data/dashboard_repository.dart';

/// Generates a branded monthly safety summary PDF report from dashboard data.
///
/// Sections:
///  - Header: "SafeTrack Monthly Safety Report — [Month Year]", Herzog branding
///  - KPI summary table: TRIR, DART Rate, Near Miss Ratio, Open Investigations, Open CAPAs
///  - TRIR trend vs benchmark (monthly values table)
///  - Incident breakdown by type (table with counts)
///  - Incident breakdown by division (table with counts)
///  - Severity distribution (table with counts)
///  - Leading indicators: Near Miss Rate, CAPA Closure Rate, Investigation Timeliness
///  - Open/overdue items requiring attention
///  - Footer: generated date, report period, "Generated by SafeTrack"
class DashboardPdfService {
  // --- Herzog brand colors for PDF ---
  static const _gold = PdfColor.fromInt(0xFFFFD100);
  static const _richBlack = PdfColor.fromInt(0xFF000000);
  static const _navyBlue = PdfColor.fromInt(0xFF1E3A5F);
  static const _darkGray = PdfColor.fromInt(0xFF58595B);
  static const _midGray = PdfColor.fromInt(0xFF6D6E71);
  static const _lightGray = PdfColor.fromInt(0xFFF5F5F5);
  static const _white = PdfColor.fromInt(0xFFFFFFFF);
  static const _successGreen = PdfColor.fromInt(0xFF1E6B38);
  static const _errorRed = PdfColor.fromInt(0xFFAB2D24);
  static const _warningAmber = PdfColor.fromInt(0xFF8A5700);

  /// Generates the monthly safety summary PDF document.
  ///
  /// [data] — the current dashboard data snapshot.
  /// [reportMonth] — the month this report covers (day is ignored).
  static Future<pw.Document> generateReport({
    required DashboardData data,
    required DateTime reportMonth,
  }) async {
    final iconData = await rootBundle.load('assets/icon.png');
    final iconImage = pw.MemoryImage(iconData.buffer.asUint8List());

    final monthLabel = DateFormat('MMMM yyyy').format(reportMonth);
    final generatedDate = DateFormat(
      'MM/dd/yyyy hh:mm a',
    ).format(DateTime.now());

    final pdf = pw.Document(
      title: 'SafeTrack Monthly Safety Report — $monthLabel',
      author: 'SafeTrack by Herzog',
      creator: 'SafeTrack PDF Export',
    );

    pdf.addPage(
      pw.MultiPage(
        pageFormat: PdfPageFormat.letter,
        margin: const pw.EdgeInsets.all(40),
        header: (context) => _buildPageHeader(monthLabel, context, iconImage),
        footer: (context) => _buildPageFooter(
          context,
          generatedDate: generatedDate,
          reportPeriod: monthLabel,
        ),
        build: (context) => [
          // --- KPI Summary ---
          _sectionHeading('KEY PERFORMANCE INDICATORS'),
          _goldAccentBar(),
          pw.SizedBox(height: 8),
          _buildKpiTable(data),
          pw.SizedBox(height: 20),

          // --- TRIR Trend vs Benchmark ---
          _sectionHeading('TRIR TREND VS BENCHMARK'),
          _goldAccentBar(),
          pw.SizedBox(height: 8),
          _buildTrirTrendTable(data),
          pw.SizedBox(height: 20),

          // --- Incident Breakdown by Type ---
          _sectionHeading('INCIDENT BREAKDOWN BY TYPE'),
          _goldAccentBar(),
          pw.SizedBox(height: 8),
          _buildIncidentByTypeTable(data),
          pw.SizedBox(height: 20),

          // --- Incident Breakdown by Division ---
          _sectionHeading('INCIDENT BREAKDOWN BY DIVISION'),
          _goldAccentBar(),
          pw.SizedBox(height: 8),
          _buildDivisionTable(data),
          pw.SizedBox(height: 20),

          // --- Severity Distribution ---
          _sectionHeading('SEVERITY DISTRIBUTION'),
          _goldAccentBar(),
          pw.SizedBox(height: 8),
          _buildSeverityTable(data),
          pw.SizedBox(height: 20),

          // --- Leading Indicators ---
          _sectionHeading('LEADING INDICATORS'),
          _goldAccentBar(),
          pw.SizedBox(height: 8),
          _buildLeadingIndicatorsTable(data),
          pw.SizedBox(height: 20),

          // --- Open / Overdue Items ---
          _sectionHeading('OPEN & OVERDUE ITEMS REQUIRING ATTENTION'),
          _goldAccentBar(),
          pw.SizedBox(height: 8),
          _buildOpenItemsSummary(data),
        ],
      ),
    );

    return pdf;
  }

  // ===== Page Header & Footer =====

  static pw.Widget _buildPageHeader(
    String monthLabel,
    pw.Context context,
    pw.MemoryImage iconImage,
  ) {
    return pw.Container(
      margin: const pw.EdgeInsets.only(bottom: 16),
      child: pw.Column(
        crossAxisAlignment: pw.CrossAxisAlignment.start,
        children: [
          pw.Row(
            mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
            crossAxisAlignment: pw.CrossAxisAlignment.start,
            children: [
              pw.Row(
                crossAxisAlignment: pw.CrossAxisAlignment.center,
                children: [
                  pw.Image(iconImage, width: 32, height: 32),
                  pw.SizedBox(width: 8),
                  pw.Column(
                    crossAxisAlignment: pw.CrossAxisAlignment.start,
                    children: [
                      pw.Text(
                        'SAFETRACK',
                        style: pw.TextStyle(
                          font: pw.Font.helveticaBold(),
                          fontSize: 22,
                          color: _navyBlue,
                          letterSpacing: 2,
                        ),
                      ),
                      pw.Text(
                        'by Herzog',
                        style: pw.TextStyle(
                          font: pw.Font.helvetica(),
                          fontSize: 10,
                          color: _midGray,
                        ),
                      ),
                    ],
                  ),
                ],
              ),
              pw.Column(
                crossAxisAlignment: pw.CrossAxisAlignment.end,
                children: [
                  pw.Text(
                    'MONTHLY SAFETY REPORT',
                    style: pw.TextStyle(
                      font: pw.Font.helveticaBold(),
                      fontSize: 16,
                      color: _richBlack,
                      letterSpacing: 1.5,
                    ),
                  ),
                  pw.SizedBox(height: 2),
                  pw.Text(
                    monthLabel,
                    style: pw.TextStyle(
                      font: pw.Font.helveticaBold(),
                      fontSize: 12,
                      color: _navyBlue,
                    ),
                  ),
                ],
              ),
            ],
          ),
          pw.SizedBox(height: 6),
          // Gold accent bar under header
          pw.Container(height: 3, color: _gold),
        ],
      ),
    );
  }

  static pw.Widget _buildPageFooter(
    pw.Context context, {
    required String generatedDate,
    required String reportPeriod,
  }) {
    return pw.Container(
      margin: const pw.EdgeInsets.only(top: 12),
      child: pw.Column(
        children: [
          pw.Container(height: 1, color: _gold),
          pw.SizedBox(height: 4),
          pw.Row(
            mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
            children: [
              pw.Text(
                'Generated by SafeTrack  |  Report Period: $reportPeriod  |  $generatedDate',
                style: pw.TextStyle(
                  font: pw.Font.helvetica(),
                  fontSize: 8,
                  color: _midGray,
                ),
              ),
              pw.Text(
                'Page ${context.pageNumber} of ${context.pagesCount}',
                style: pw.TextStyle(
                  font: pw.Font.helvetica(),
                  fontSize: 8,
                  color: _midGray,
                ),
              ),
            ],
          ),
        ],
      ),
    );
  }

  // ===== KPI Summary Table =====

  static pw.Widget _buildKpiTable(DashboardData data) {
    return pw.Table(
      border: pw.TableBorder.all(color: PdfColor.fromInt(0xFFD1D3D4)),
      columnWidths: {
        0: const pw.FlexColumnWidth(2),
        1: const pw.FlexColumnWidth(1),
      },
      children: [
        pw.TableRow(
          decoration: const pw.BoxDecoration(color: _navyBlue),
          children: [_tableHeader('Metric'), _tableHeader('Value')],
        ),
        _dataRow(
          'TRIR (Total Recordable Incident Rate)',
          data.trir.toStringAsFixed(2),
        ),
        _dataRow('DART Rate', data.dartRate.toStringAsFixed(2)),
        _dataRow('Near Miss Ratio', data.nearMissRatio.toStringAsFixed(2)),
        _dataRow('Open Investigations', data.openInvestigations.toString()),
        _dataRow('Open CAPAs', data.openCapas.toString()),
        _dataRow(
          'Lost Time Incidents YTD',
          data.lostTimeIncidentsYtd.toString(),
        ),
      ],
    );
  }

  // ===== TRIR Trend vs Benchmark Table =====

  static pw.Widget _buildTrirTrendTable(DashboardData data) {
    if (data.trirTrend.isEmpty) {
      return _bodyText('No TRIR trend data available.');
    }

    return pw.Table(
      border: pw.TableBorder.all(color: PdfColor.fromInt(0xFFD1D3D4)),
      columnWidths: {
        0: const pw.FlexColumnWidth(2),
        1: const pw.FlexColumnWidth(1),
        2: const pw.FlexColumnWidth(1),
        3: const pw.FlexColumnWidth(1),
      },
      children: [
        pw.TableRow(
          decoration: const pw.BoxDecoration(color: _navyBlue),
          children: [
            _tableHeader('Month'),
            _tableHeader('TRIR'),
            _tableHeader('Benchmark'),
            _tableHeader('Status'),
          ],
        ),
        ...data.trirTrend.map((entry) {
          final aboveBenchmark = entry.trir > data.trirBenchmark;
          final statusColor = aboveBenchmark ? _errorRed : _successGreen;
          final statusText = aboveBenchmark ? 'Above' : 'At/Below';
          return pw.TableRow(
            children: [
              _tableCell(entry.month),
              _tableCell(entry.trir.toStringAsFixed(2)),
              _tableCell(data.trirBenchmark.toStringAsFixed(2)),
              pw.Padding(
                padding: const pw.EdgeInsets.all(4),
                child: pw.Text(
                  statusText,
                  style: pw.TextStyle(
                    font: pw.Font.helveticaBold(),
                    fontSize: 8,
                    color: statusColor,
                  ),
                ),
              ),
            ],
          );
        }),
      ],
    );
  }

  // ===== Incident Breakdown by Type =====

  static pw.Widget _buildIncidentByTypeTable(DashboardData data) {
    if (data.incidentTrend.isEmpty) {
      return _bodyText('No incident type data available.');
    }

    // Aggregate type totals across all months
    int totalInjury = 0;
    int totalNearMiss = 0;
    int totalPropertyDamage = 0;
    int totalEnvironmental = 0;
    int totalVehicle = 0;
    int totalFire = 0;
    int totalUtilityStrike = 0;

    for (final m in data.incidentTrend) {
      totalInjury += m.injury;
      totalNearMiss += m.nearMiss;
      totalPropertyDamage += m.propertyDamage;
      totalEnvironmental += m.environmental;
      totalVehicle += m.vehicle;
      totalFire += m.fire;
      totalUtilityStrike += m.utilityStrike;
    }

    final types = <MapEntry<String, int>>[
      MapEntry('Injury', totalInjury),
      MapEntry('Near Miss', totalNearMiss),
      MapEntry('Property Damage', totalPropertyDamage),
      MapEntry('Environmental', totalEnvironmental),
      MapEntry('Vehicle', totalVehicle),
      MapEntry('Fire', totalFire),
      MapEntry('Utility Strike', totalUtilityStrike),
    ];

    final grandTotal = types.fold<int>(0, (sum, e) => sum + e.value);

    return pw.Table(
      border: pw.TableBorder.all(color: PdfColor.fromInt(0xFFD1D3D4)),
      columnWidths: {
        0: const pw.FlexColumnWidth(2),
        1: const pw.FlexColumnWidth(1),
        2: const pw.FlexColumnWidth(1),
      },
      children: [
        pw.TableRow(
          decoration: const pw.BoxDecoration(color: _navyBlue),
          children: [
            _tableHeader('Incident Type'),
            _tableHeader('Count'),
            _tableHeader('% of Total'),
          ],
        ),
        ...types.where((e) => e.value > 0).map((entry) {
          final pct = grandTotal > 0
              ? (entry.value / grandTotal * 100).toStringAsFixed(1)
              : '0.0';
          return _dataRow3(entry.key, entry.value.toString(), '$pct%');
        }),
        // Total row
        pw.TableRow(
          decoration: const pw.BoxDecoration(color: _lightGray),
          children: [
            pw.Padding(
              padding: const pw.EdgeInsets.all(4),
              child: pw.Text(
                'Total',
                style: pw.TextStyle(
                  font: pw.Font.helveticaBold(),
                  fontSize: 9,
                  color: _richBlack,
                ),
              ),
            ),
            pw.Padding(
              padding: const pw.EdgeInsets.all(4),
              child: pw.Text(
                grandTotal.toString(),
                style: pw.TextStyle(
                  font: pw.Font.helveticaBold(),
                  fontSize: 9,
                  color: _richBlack,
                ),
              ),
            ),
            pw.Padding(
              padding: const pw.EdgeInsets.all(4),
              child: pw.Text(
                '100%',
                style: pw.TextStyle(
                  font: pw.Font.helveticaBold(),
                  fontSize: 9,
                  color: _richBlack,
                ),
              ),
            ),
          ],
        ),
      ],
    );
  }

  // ===== Incident Breakdown by Division =====

  static pw.Widget _buildDivisionTable(DashboardData data) {
    if (data.incidentsByDivision.isEmpty) {
      return _bodyText('No division data available.');
    }

    final grandTotal = data.incidentsByDivision.fold<int>(
      0,
      (sum, d) => sum + d.count,
    );

    return pw.Table(
      border: pw.TableBorder.all(color: PdfColor.fromInt(0xFFD1D3D4)),
      columnWidths: {
        0: const pw.FlexColumnWidth(2),
        1: const pw.FlexColumnWidth(1),
        2: const pw.FlexColumnWidth(1),
      },
      children: [
        pw.TableRow(
          decoration: const pw.BoxDecoration(color: _navyBlue),
          children: [
            _tableHeader('Division'),
            _tableHeader('Count'),
            _tableHeader('% of Total'),
          ],
        ),
        ...data.incidentsByDivision.map((d) {
          final pct = grandTotal > 0
              ? (d.count / grandTotal * 100).toStringAsFixed(1)
              : '0.0';
          return _dataRow3(d.division, d.count.toString(), '$pct%');
        }),
        // Total row
        pw.TableRow(
          decoration: const pw.BoxDecoration(color: _lightGray),
          children: [
            _boldCell('Total'),
            _boldCell(grandTotal.toString()),
            _boldCell('100%'),
          ],
        ),
      ],
    );
  }

  // ===== Severity Distribution =====

  static pw.Widget _buildSeverityTable(DashboardData data) {
    if (data.severityDistribution.isEmpty) {
      return _bodyText('No severity data available.');
    }

    final grandTotal = data.severityDistribution.fold<int>(
      0,
      (sum, s) => sum + s.count,
    );

    return pw.Table(
      border: pw.TableBorder.all(color: PdfColor.fromInt(0xFFD1D3D4)),
      columnWidths: {
        0: const pw.FlexColumnWidth(2),
        1: const pw.FlexColumnWidth(1),
        2: const pw.FlexColumnWidth(1),
      },
      children: [
        pw.TableRow(
          decoration: const pw.BoxDecoration(color: _navyBlue),
          children: [
            _tableHeader('Severity'),
            _tableHeader('Count'),
            _tableHeader('% of Total'),
          ],
        ),
        ...data.severityDistribution.map((s) {
          final pct = grandTotal > 0
              ? (s.count / grandTotal * 100).toStringAsFixed(1)
              : '0.0';
          return _dataRow3(s.severity, s.count.toString(), '$pct%');
        }),
        pw.TableRow(
          decoration: const pw.BoxDecoration(color: _lightGray),
          children: [
            _boldCell('Total'),
            _boldCell(grandTotal.toString()),
            _boldCell('100%'),
          ],
        ),
      ],
    );
  }

  // ===== Leading Indicators =====

  static pw.Widget _buildLeadingIndicatorsTable(DashboardData data) {
    final li = data.leadingIndicators;

    return pw.Table(
      border: pw.TableBorder.all(color: PdfColor.fromInt(0xFFD1D3D4)),
      columnWidths: {
        0: const pw.FlexColumnWidth(2),
        1: const pw.FlexColumnWidth(1),
        2: const pw.FlexColumnWidth(1),
        3: const pw.FlexColumnWidth(1),
      },
      children: [
        pw.TableRow(
          decoration: const pw.BoxDecoration(color: _navyBlue),
          children: [
            _tableHeader('Indicator'),
            _tableHeader('Target'),
            _tableHeader('Actual'),
            _tableHeader('Status'),
          ],
        ),
        _indicatorRow(
          'Near Miss Reporting Rate',
          li.nearMissReportingRate,
          higherIsBetter: true,
        ),
        _indicatorRow(
          'CAPA Closure Rate',
          li.capaClosureRate,
          higherIsBetter: true,
        ),
        _indicatorRow(
          'Investigation Timeliness',
          li.investigationTimeliness,
          higherIsBetter: true,
        ),
      ],
    );
  }

  static pw.TableRow _indicatorRow(
    String name,
    IndicatorMetric metric, {
    required bool higherIsBetter,
  }) {
    final meetingTarget = higherIsBetter
        ? metric.actual >= metric.target
        : metric.actual <= metric.target;
    final statusColor = meetingTarget ? _successGreen : _warningAmber;
    final statusText = meetingTarget ? 'On Target' : 'Below Target';

    return pw.TableRow(
      children: [
        _tableCell(name),
        _tableCell('${metric.target.toStringAsFixed(1)}%'),
        _tableCell('${metric.actual.toStringAsFixed(1)}%'),
        pw.Padding(
          padding: const pw.EdgeInsets.all(4),
          child: pw.Text(
            statusText,
            style: pw.TextStyle(
              font: pw.Font.helveticaBold(),
              fontSize: 8,
              color: statusColor,
            ),
          ),
        ),
      ],
    );
  }

  // ===== Open / Overdue Items =====

  static pw.Widget _buildOpenItemsSummary(DashboardData data) {
    final items = <pw.Widget>[];

    if (data.openInvestigations > 0) {
      items.add(
        _bulletItem(
          '${data.openInvestigations} open investigation(s) pending completion',
          color: _warningAmber,
        ),
      );
    }

    if (data.openCapas > 0) {
      items.add(
        _bulletItem(
          '${data.openCapas} open CAPA(s) requiring action',
          color: _warningAmber,
        ),
      );
    }

    // Flag recent incidents that are still open
    final openIncidents = data.recentIncidents
        .where(
          (i) =>
              i.status.toLowerCase() == 'open' ||
              i.status.toLowerCase() == 'in progress',
        )
        .toList();

    if (openIncidents.isNotEmpty) {
      items.add(
        _bulletItem(
          '${openIncidents.length} recent incident(s) still open or in progress:',
          color: _warningAmber,
        ),
      );
      for (final incident in openIncidents) {
        items.add(
          pw.Padding(
            padding: const pw.EdgeInsets.only(left: 20, top: 2),
            child: _bodyText(
              '#${incident.id} — ${incident.type} (${incident.severity}) — ${incident.division} — ${incident.date}',
            ),
          ),
        );
      }
    }

    // Check leading indicators below target
    final li = data.leadingIndicators;
    if (li.capaClosureRate.actual < li.capaClosureRate.target) {
      items.add(
        _bulletItem(
          'CAPA Closure Rate (${li.capaClosureRate.actual.toStringAsFixed(1)}%) '
          'is below target (${li.capaClosureRate.target.toStringAsFixed(1)}%)',
          color: _errorRed,
        ),
      );
    }
    if (li.investigationTimeliness.actual < li.investigationTimeliness.target) {
      items.add(
        _bulletItem(
          'Investigation Timeliness (${li.investigationTimeliness.actual.toStringAsFixed(1)}%) '
          'is below target (${li.investigationTimeliness.target.toStringAsFixed(1)}%)',
          color: _errorRed,
        ),
      );
    }
    if (li.nearMissReportingRate.actual < li.nearMissReportingRate.target) {
      items.add(
        _bulletItem(
          'Near Miss Reporting Rate (${li.nearMissReportingRate.actual.toStringAsFixed(1)}%) '
          'is below target (${li.nearMissReportingRate.target.toStringAsFixed(1)}%)',
          color: _errorRed,
        ),
      );
    }

    if (items.isEmpty) {
      return pw.Container(
        padding: const pw.EdgeInsets.all(12),
        decoration: pw.BoxDecoration(
          color: const PdfColor.fromInt(0xFFD4EDDA),
          borderRadius: pw.BorderRadius.circular(4),
        ),
        child: pw.Text(
          'No open or overdue items — all indicators are on target.',
          style: pw.TextStyle(
            font: pw.Font.helveticaBold(),
            fontSize: 10,
            color: _successGreen,
          ),
        ),
      );
    }

    return pw.Column(
      crossAxisAlignment: pw.CrossAxisAlignment.start,
      children: items,
    );
  }

  static pw.Widget _bulletItem(String text, {PdfColor color = _darkGray}) {
    return pw.Padding(
      padding: const pw.EdgeInsets.symmetric(vertical: 3),
      child: pw.Row(
        crossAxisAlignment: pw.CrossAxisAlignment.start,
        children: [
          pw.Container(
            width: 6,
            height: 6,
            margin: const pw.EdgeInsets.only(top: 3, right: 8),
            decoration: pw.BoxDecoration(
              color: color,
              shape: pw.BoxShape.circle,
            ),
          ),
          pw.Expanded(
            child: pw.Text(
              text,
              style: pw.TextStyle(
                font: pw.Font.helvetica(),
                fontSize: 10,
                color: color,
              ),
            ),
          ),
        ],
      ),
    );
  }

  // ===== Shared Table / Text Helpers =====

  static pw.Widget _sectionHeading(String title) {
    return pw.Text(
      title,
      style: pw.TextStyle(
        font: pw.Font.helveticaBold(),
        fontSize: 14,
        color: _navyBlue,
        letterSpacing: 1.2,
      ),
    );
  }

  static pw.Widget _goldAccentBar() {
    return pw.Container(
      height: 2,
      width: double.infinity,
      color: _gold,
      margin: const pw.EdgeInsets.only(top: 2),
    );
  }

  static pw.Widget _bodyText(String text, {PdfColor color = _darkGray}) {
    return pw.Text(
      text,
      style: pw.TextStyle(
        font: pw.Font.helvetica(),
        fontSize: 10,
        color: color,
      ),
    );
  }

  static pw.Widget _tableHeader(String text) {
    return pw.Padding(
      padding: const pw.EdgeInsets.all(4),
      child: pw.Text(
        text,
        style: pw.TextStyle(
          font: pw.Font.helveticaBold(),
          fontSize: 8,
          color: _white,
        ),
      ),
    );
  }

  static pw.Widget _tableCell(String text) {
    return pw.Padding(
      padding: const pw.EdgeInsets.all(4),
      child: pw.Text(
        text.isNotEmpty ? text : '-',
        style: pw.TextStyle(
          font: pw.Font.helvetica(),
          fontSize: 8,
          color: _darkGray,
        ),
      ),
    );
  }

  static pw.Widget _boldCell(String text) {
    return pw.Padding(
      padding: const pw.EdgeInsets.all(4),
      child: pw.Text(
        text,
        style: pw.TextStyle(
          font: pw.Font.helveticaBold(),
          fontSize: 9,
          color: _richBlack,
        ),
      ),
    );
  }

  /// Two-column data row (label + value).
  static pw.TableRow _dataRow(String label, String value) {
    return pw.TableRow(children: [_tableCell(label), _tableCell(value)]);
  }

  /// Three-column data row.
  static pw.TableRow _dataRow3(String col1, String col2, String col3) {
    return pw.TableRow(
      children: [_tableCell(col1), _tableCell(col2), _tableCell(col3)],
    );
  }
}
